---
kind: Template
apiVersion: v1
labels:
  app: kite-proxy-composer
  template: kite-proxy-composer-template
metadata:
  name: kite-proxy-composer
  annotations:
    openshift.io/display-name: kite proxy composer
    tags: kite,proxy,kite-proxy-composer,composer

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: ${KITE_PROXY_NAME}
      name: ${KITE_PROXY_NAME}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      labels:
        app: ${KITE_PROXY_NAME}
      name: ${KITE_PROXY_NAME}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${KITE_PROXY_IMAGE_STREAM_TAG}
      resources: {}
      source:
        type: Git
        contextDir: ${CONTEXTDIR}
        git:
          uri: ${REPO_URL}
          ref: ${REPO_REF}
      strategy:
        type: Docker
        dockerStrategy:
          noCache: true
          forcePull: true
      triggers:
        - type: ConfigChange
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${KITE_PROXY_NAME}
    spec:
      replicas: 1
      selector:
        name: ${KITE_PROXY_NAME}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: ${KITE_PROXY_NAME}
        spec:
          containers:
            - name: ${KITE_PROXY_NAME}
              image: ${KITE_PROXY_IMAGE_STREAM_TAG}
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  memory: "2Gi"
                  cpu: "2000m"
                requests:
                  memory: "500Mi"
                  cpu: "512m"
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - name: os-secret
                  mountPath: /run/secrets/os-secret
                  readOnly: true
                - name: gcp-sa-file
                  mountPath: /run/secrets/gcp-sa-file
                  readOnly: true
                - name: crc-ps-file
                  mountPath: /run/secrets/crc-ps-file
                  readOnly: true
                - name: beaker-keytab-file
                  mountPath: /run/secrets/beaker-keytab-file
                  readOnly: true
                - name: kerberos-conf
                  mountPath: /run/secrets/kerberos-conf
                  readOnly: true
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: kite-aws-access-key-id
                      key: id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kite-aws-secret-access-key
                      key: secret
                - name: SQS_QUEUE_COMPOSER
                  valueFrom:
                    secretKeyRef:
                      name: kite-sqs-queue-name-composer
                      key: queue_name
                - name: SQS_REGION
                  valueFrom:
                    secretKeyRef:
                      name: kite-sqs-queue-region
                      key: queue_region
                - name: PERSONAL_ACCESS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kite-kitebot-pat
                      key: kitebot_pat
                - name: GCP_SERVICE_ACCOUNT_NAME
                  valueFrom:
                    secretKeyRef:
                      name: gcp-service-account-name-composer
                      key: gcp_sa_name
                - name: GCP_PROJECT
                  valueFrom:
                    secretKeyRef:
                      name: gcp-project-composer
                      key: gcp_project_name
                - name: PULL_SECRET_FILE
                  valueFrom:
                    secretKeyRef:
                      name: crc-pull-secret-file
                      key: crc_ps_file
                - name: DOWNLOAD_NODE
                  valueFrom:
                    secretKeyRef:
                      name: rhel-repo-download-node
                      key: download_node
                - name: OS_CLIENT_CONFIG_FILE
                  value: "/run/secrets/os-secret/clouds.yaml"
                - name: GCP_SERVICE_ACCOUNT_FILE
                  value: "/run/secrets/gcp-sa-file/edge-qe-dev-91556f820ec8.json"
                - name: ANSIBLE_LOCAL_TEMP
                  value: "/home/proxy/.ansible/tmp"
                - name: ANSIBLE_HOME
                  value: "/home/proxy/.ansible"
                - name: ANSIBLE_COLLECTIONS_PATH
                  value: "/home/proxy/.ansible/collections"
                - name: CLOUDSDK_CONFIG
                  value: "/home/proxy/gcloud"
                - name: KRB5_CONFIG
                  value: "/run/secrets/kerberos-conf/krb5.conf"
          volumes:
            - name: os-secret
              secret:
                defaultMode: 420
                secretName: kite-openstack-cerdential-02
            - name: gcp-sa-file
              secret:
                defaultMode: 420
                secretName: gcp-sa-file-composer
            - name: crc-ps-file
              secret:
                defaultMode: 420
                secretName: crc-ps-file
            - name: beaker-keytab-file
              secret:
                defaultMode: 420
                secretName: beaker-keytab-file
            - name: kerberos-conf
              secret:
                defaultMode: 420
                secretName: kerberos-conf
          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers:
        - type: "ConfigChange"
        - type: "ImageChange"
          imageChangeParams:
            automatic: true
            containerNames:
              - ${KITE_PROXY_NAME}
            from:
              kind: "ImageStreamTag"
              name: ${KITE_PROXY_IMAGE_STREAM_TAG}
# global parameters
parameters:
  - description: Git repository with Dockerfile and master entrypoint.
    displayName: Repository URL
    name: REPO_URL
    value: https://github.com/virt-s1/kite-action.git
    required: true
  - description: The sub-directory inside the repository.
    displayName: Context Directory
    name: CONTEXTDIR
    value: proxy
  - description: The git ref or tag to use for customization.
    displayName: Git Reference
    name: REPO_REF
    value: composer_ci
  - name: KITE_PROXY_NAME
    displayName: kite proxy APP name
    description: The name of the kite proxy application.
    value: kite-proxy-composer
  - name: KITE_PROXY_IMAGE_STREAM_TAG
    displayName: kite proxy ImageStreamTag
    description: Name of the ImageStreamTag to be used for the kite proxy image.
    value: kite-proxy-composer:latest
