---
kind: Template
apiVersion: v1
labels:
  app: kite-proxy-dev
  template: kite-proxy-template-dev
metadata:
  name: kite-proxy-dev
  annotations:
    openshift.io/display-name: kite proxy dev
    tags: kite,proxy,kite-proxy-dev,dev

objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${KITE_PROXY_NAME}
    spec:
      replicas: 1
      selector:
        name: ${KITE_PROXY_NAME}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: ${KITE_PROXY_NAME}
        spec:
          containers:
            - name: ${KITE_PROXY_NAME}
              image: ${KITE_PROXY_IMAGE}
              imagePullPolicy: Always
              resources:
                limits:
                  memory: "2Gi"
                  cpu: "2000m"
                requests:
                  memory: "500Mi"
                  cpu: "512m"
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - name: os-secret
                  mountPath: /run/secrets/os-secret
                  readOnly: true
                - name: gcp-sa-file
                  mountPath: /run/secrets/gcp-sa-file
                  readOnly: true
                - name: crc-ps-file
                  mountPath: /run/secrets/crc-ps-file
                  readOnly: true
                - name: beaker-keytab-file
                  mountPath: /run/secrets/beaker-keytab-file
                  readOnly: true
                - name: kerberos-conf
                  mountPath: /run/secrets/kerberos-conf
                  readOnly: true
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: kite-aws-access-key-id
                      key: id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kite-aws-secret-access-key
                      key: secret
                - name: SQS_QUEUE_DEV
                  valueFrom:
                    secretKeyRef:
                      name: kite-sqs-queue-name-dev
                      key: queue_name
                - name: SQS_REGION
                  valueFrom:
                    secretKeyRef:
                      name: kite-sqs-queue-region
                      key: queue_region
                - name: PERSONAL_ACCESS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kite-kitebot-pat
                      key: kitebot_pat
                - name: GCP_SERVICE_ACCOUNT_NAME
                  valueFrom:
                    secretKeyRef:
                      name: gcp-service-account-name
                      key: gcp_sa_name
                - name: GCP_PROJECT
                  valueFrom:
                    secretKeyRef:
                      name: gcp-project
                      key: gcp_project_name
                - name: PULL_SECRET_FILE
                  valueFrom:
                    secretKeyRef:
                      name: crc-pull-secret-file
                      key: crc_ps_file
                - name: DOWNLOAD_NODE
                  valueFrom:
                    secretKeyRef:
                      name: rhel-repo-download-node
                      key: download_node
                - name: OS_CLIENT_CONFIG_FILE
                  value: "/run/secrets/os-secret/clouds.yaml"
                - name: GCP_SERVICE_ACCOUNT_FILE
                  value: "/run/secrets/gcp-sa-file/gcp_service_account.json"
                - name: ANSIBLE_LOCAL_TEMP
                  value: "/home/proxy/.ansible/tmp"
                - name: ANSIBLE_HOME
                  value: "/home/proxy/.ansible"
                - name: ANSIBLE_COLLECTIONS_PATH
                  value: "/home/proxy/.ansible/collections"
                - name: CLOUDSDK_CONFIG
                  value: "/home/proxy/gcloud"
                - name: KRB5_CONFIG
                  value: "/run/secrets/kerberos-conf/krb5.conf"
          volumes:
            - name: os-secret
              secret:
                defaultMode: 420
                secretName: kite-openstack-cerdential
            - name: gcp-sa-file
              secret:
                defaultMode: 420
                secretName: gcp-sa-file
            - name: crc-ps-file
              secret:
                defaultMode: 420
                secretName: crc-ps-file
            - name: beaker-keytab-file
              secret:
                defaultMode: 420
                secretName: beaker-keytab-file
            - name: kerberos-conf
              secret:
                defaultMode: 420
                secretName: kerberos-conf
          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers:
        - type: "ConfigChange"
# global parameters
parameters:
  - description: Git repository with Dockerfile and master entrypoint.
    displayName: Repository URL
    name: REPO_URL
    value: https://github.com/virt-s1/kite-action.git
    required: true
  - name: KITE_PROXY_NAME
    displayName: kite proxy APP name
    description: The name of the kite proxy application.
    value: kite-proxy-dev
  - name: KITE_PROXY_IMAGE
    displayName: kite proxy Image
    description: Name of the Image to be used for the kite proxy image.
    value: quay.io/rhel-edge/kite-proxy:dev
