---
- hosts: localhost
  become: no
  vars:
    prefix: "kite-webhook"
    project: "dev"
    aws_profile: "{{ lookup('env', 'AWS_PROFILE') }}"
    aws_region: "{{ lookup('env', 'AWS_REGION') }}"

  tasks:
    - name: create temporary zip file folder
      tempfile:
        state: directory
        prefix: "zip-"
      register: temp_result

    - name: create a zip archive
      community.general.archive:
        path: "{{ playbook_dir }}/../webhook/webhook.py"
        dest: "{{ temp_result.path }}/webhook.zip"
        format: zip

    - name: update lambda function code
      command: aws lambda update-function-code --function-name "{{ prefix }}-{{ project }}" --zip-file "fileb://{{ temp_result.path }}/webhook.zip" --output json --profile kite --region "{{ aws_region }}"

    - name: wait until function state is Active
      amazon.aws.lambda_info:
        function_name: "{{ prefix }}-{{ project }}"
        query: all
      register: version_result
      retries: 30
      delay: 2
      until: version_result.functions[0].state == "Active"

    - set_fact:
        function_arn: "{{ version_result.functions[0].function_arn }}"

    - name: publish lambda function
      command: aws lambda publish-version --function-name "{{ prefix }}-{{ project }}" --output json --profile kite --region "{{ aws_region }}" --query "Version"
      register: publish_result

    - name: configure function alias
      amazon.aws.lambda_alias:
        name: "{{ project }}"
        function_name: "{{ prefix }}-{{ project }}"
        function_version: "{{ publish_result.stdout | replace('\"', '') | int }}"
