---
- hosts: localhost
  gather_facts: no
  become: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: local
    cloud_profile: "rhos-d"

  tasks:
    - name: Delete instance
      openstack.cloud.server:
        cloud: "{{ cloud_profile }}"
        name: "{{ instance_name }}"
        state: absent
      ignore_errors: yes
