---
- hosts: openstack
  gather_facts: no
  become: no
  vars:
    cloud_profile: "rhos-01"
    date_label: "{{ lookup('pipe', 'date +%y%m%d') }}"

  tasks:
    - name: create keypair for rhel-edge test
      openstack.cloud.keypair:
        cloud: "{{ cloud_profile }}"
        state: present
        name: "rhel-edge"
        public_key_file: key/ostree_key.pub

    - name: "deploy RHEL instance"
      openstack.cloud.server:
        cloud: "{{ cloud_profile }}"
        name: "{{ os }}-{{ date_label }}"
        image: "{{ images[os] }}"
        flavor: "ci.standard.large"
        network: "shared_net_9"
        key_name: "rhel-edge"
        security_groups: ssh_only
        auto_ip: yes
        config_drive: yes
        wait: yes
        timeout: 600
        userdata: |
          #cloud-config
          users:
            - default
            - name: admin
              gecos: Administrator
              groups: users,wheel
              sudo: ALL=(ALL) NOPASSWD:ALL
              ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzxo5dEcS+LDK/OFAfHo6740EyoDM8aYaCkBala0FnWfMMTOq7PQe04ahB0eFLS3IlQtK5bpgzxBdFGVqF6uT5z4hhaPjQec0G3+BD5Pxo6V+SxShKZo+ZNGU3HVrF9p2V7QH0YFQj5B8F6AicA3fYh2BVUFECTPuMpy5A52ufWu0r4xOFmbU7SIhRQRAQz2u4yjXqBsrpYptAvyzzoN4gjUhNnwOHSPsvFpWoBFkWmqn0ytgHg3Vv9DlHW+45P02QH1UFedXR2MqLnwRI30qqtaOkVS+9rE/dhnR+XPpHHG+hv2TgMDAuQ3IK7Ab5m/yCbN73cxFifH4LST0vVG3Jx45xn+GTeHHhfkAfBSCtya6191jixbqyovpRunCBKexI5cfRPtWOitM3m7Mq26r7LpobMM+oOLUm4p0KKNIthWcmK9tYwXWSuGGfUQ+Y8gt7E0G06ZGbCPHOrxJ8lYQqXsif04piONPA/c9Hq43O99KPNGShONCS9oPFdOLRT3U= ostree-image-test
          yum_repos:
            baseos:
              name: rhel-baseos
              baseurl: "{{ repos[os]['baseos'] }}"
              enabled: true
              gpgcheck: false
              sslverify: false
            appstream:
              name: rhel-appstream
              baseurl: "{{ repos[os]['appstream'] }}"
              enabled: true
              gpgcheck: false
              sslverify: false
          packages:
            - python3
            - python3-dnf
      register: tmp_instance_result
      when: "'rhel' in os"

    # avoid registering a variable when a “when” condition is *not* met
    - set_fact:
        instance_result: "{{ tmp_instance_result }}"
      when: tmp_instance_result.changed

    - name: "deploy CentOS Stream instance"
      openstack.cloud.server:
        cloud: "{{ cloud_profile }}"
        name: "{{ os }}-{{ date_label }}"
        image: "{{ images[os] }}"
        flavor: "ci.standard.large"
        network: "shared_net_9"
        key_name: "rhel-edge"
        security_groups: ssh_only
        auto_ip: yes
        config_drive: yes
        wait: yes
        timeout: 600
        userdata: |
          #cloud-config
          packages:
            - python3
            - python3-dnf
          users:
            - default
            - name: admin
              gecos: Administrator
              groups: users,wheel
              sudo: ALL=(ALL) NOPASSWD:ALL
              ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzxo5dEcS+LDK/OFAfHo6740EyoDM8aYaCkBala0FnWfMMTOq7PQe04ahB0eFLS3IlQtK5bpgzxBdFGVqF6uT5z4hhaPjQec0G3+BD5Pxo6V+SxShKZo+ZNGU3HVrF9p2V7QH0YFQj5B8F6AicA3fYh2BVUFECTPuMpy5A52ufWu0r4xOFmbU7SIhRQRAQz2u4yjXqBsrpYptAvyzzoN4gjUhNnwOHSPsvFpWoBFkWmqn0ytgHg3Vv9DlHW+45P02QH1UFedXR2MqLnwRI30qqtaOkVS+9rE/dhnR+XPpHHG+hv2TgMDAuQ3IK7Ab5m/yCbN73cxFifH4LST0vVG3Jx45xn+GTeHHhfkAfBSCtya6191jixbqyovpRunCBKexI5cfRPtWOitM3m7Mq26r7LpobMM+oOLUm4p0KKNIthWcmK9tYwXWSuGGfUQ+Y8gt7E0G06ZGbCPHOrxJ8lYQqXsif04piONPA/c9Hq43O99KPNGShONCS9oPFdOLRT3U= ostree-image-test
      register: tmp_instance_result
      when: "'centos' in os"

    # avoid registering a variable when a “when” condition is *not* met
    - set_fact:
        instance_result: "{{ tmp_instance_result }}"
      when: tmp_instance_result.changed

    - name: "deploy Fedora instance"
      openstack.cloud.server:
        cloud: "{{ cloud_profile }}"
        name: "{{ os }}-{{ date_label }}"
        image: "{{ images[os] }}"
        flavor: "ci.standard.large"
        network: "shared_net_9"
        key_name: "rhel-edge"
        security_groups: ssh_only
        auto_ip: yes
        config_drive: yes
        wait: yes
        timeout: 600
        userdata: |
          #cloud-config
          packages:
            - python3
            - python3-dnf
          users:
            - default
            - name: admin
              gecos: Administrator
              groups: users,wheel
              sudo: ALL=(ALL) NOPASSWD:ALL
              ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzxo5dEcS+LDK/OFAfHo6740EyoDM8aYaCkBala0FnWfMMTOq7PQe04ahB0eFLS3IlQtK5bpgzxBdFGVqF6uT5z4hhaPjQec0G3+BD5Pxo6V+SxShKZo+ZNGU3HVrF9p2V7QH0YFQj5B8F6AicA3fYh2BVUFECTPuMpy5A52ufWu0r4xOFmbU7SIhRQRAQz2u4yjXqBsrpYptAvyzzoN4gjUhNnwOHSPsvFpWoBFkWmqn0ytgHg3Vv9DlHW+45P02QH1UFedXR2MqLnwRI30qqtaOkVS+9rE/dhnR+XPpHHG+hv2TgMDAuQ3IK7Ab5m/yCbN73cxFifH4LST0vVG3Jx45xn+GTeHHhfkAfBSCtya6191jixbqyovpRunCBKexI5cfRPtWOitM3m7Mq26r7LpobMM+oOLUm4p0KKNIthWcmK9tYwXWSuGGfUQ+Y8gt7E0G06ZGbCPHOrxJ8lYQqXsif04piONPA/c9Hq43O99KPNGShONCS9oPFdOLRT3U= ostree-image-test
      register: tmp_instance_result
      when: "'fedora' in os"

    # avoid registering a variable when a “when” condition is *not* met
    - set_fact:
        instance_result: "{{ tmp_instance_result }}"
      when: tmp_instance_result.changed

    - name: waits until instance is reachable
      wait_for:
        host: "{{ instance_result.openstack.public_v4 }}"
        port: 22
        search_regex: OpenSSH
        delay: 10

    - name: add instance ip into host group guest
      add_host:
        name: "{{ instance_result.openstack.public_v4 }}"
        groups: guest

    - name: keep private key permission to 600
      file:
        path: "key/ostree_key"
        mode: "0600"

    - name: ensure cloud-init has finished
      raw: test -f /var/lib/cloud/instance/boot-finished
      retries: 60
      register: cloud_init_check
      changed_when: false
      until: cloud_init_check is success
      delegate_to: "{{ instance_result.openstack.public_v4 }}"

- hosts: guest
  gather_facts: yes
  become: no

  tasks:
