---
name: Build kite-proxy container for composer ci

on:
  workflow_dispatch:

jobs:
  build-kite-proxy-composer-container:
    runs-on: container-runner
    container:
      image: quay.io/fedora/fedora:38-x86_64
      options: --privileged
    steps:
      - uses: actions/checkout@v3
        with:
          ref: composer_ci

      - name: Install podman
        run: sudo dnf install -y podman

      - name: Build kite-proxy image and upload to quay.io
        run: |
          podman build -t "kite-proxy:composer_ci" -f proxy/Dockerfile proxy
          podman push --creds "${QUAY_USER}":"${QUAY_PASS}" "kite-proxy:composer_ci" "quay.io/rhel-edge/kite-proxy:composer_ci"
        env:
          QUAY_USER: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASS: ${{ secrets.QUAY_PASSWORD }}
